$background = 0c0f0b
$onBackground = e0e8dc
$surface = 0c0f0b
$surfaceDim = 0c0f0b
$surfaceBright = 272e26
$surfaceContainerLowest = 000000
$surfaceContainerLow = 101510
$surfaceContainer = 151b15
$surfaceContainerHigh = 1b211b
$surfaceContainerHighest = 202820
$onSurface = e0e8dc
$surfaceVariant = 202820
$onSurfaceVariant = a5ada2
$outline = 70786e
$outlineVariant = 424a41
$inverseSurface = f8faf3
$inverseOnSurface = 525651
$shadow = 000000
$scrim = 000000
$surfaceTint = abd0aa
$primary = abd0aa
$primaryDim = 9ec29d
$onPrimary = 28472b
$primaryContainer = 3a5a3c
$onPrimaryContainer = c8edc5
$inversePrimary = 466748
$primaryFixed = c7ecc5
$primaryFixedDim = b9deb7
$onPrimaryFixed = 27462a
$onPrimaryFixedVariant = 436344
$secondary = b8ccb5
$secondaryDim = abbea8
$onSecondary = 334433
$secondaryContainer = 2f402f
$onSecondaryContainer = b1c5ae
$secondaryFixed = d4e8d0
$secondaryFixedDim = c6dac3
$onSecondaryFixed = 334333
$onSecondaryFixedVariant = 4e604e
$tertiary = f8ffbc
$tertiaryDim = e1e8a7
$onTertiary = 5d632f
$tertiaryContainer = eaf0af
$onTertiaryContainer = 545a28
$tertiaryFixed = f8ffbc
$tertiaryFixedDim = eaf0af
$onTertiaryFixed = 4b501f
$onTertiaryFixedVariant = 676e39
$error = f97758
$errorDim = c44f34
$onError = 450900
$errorContainer = 85230a
$onErrorContainer = ff9b82
$primaryPaletteKeyColor = 5d7f5e
$secondaryPaletteKeyColor = 6a7c68
$tertiaryPaletteKeyColor = 757b45
$neutralPaletteKeyColor = 757872
$neutralVariantPaletteKeyColor = 71796f
$errorPaletteKeyColor = c75236
$primary_paletteKeyColor = 5d7f5e
$secondary_paletteKeyColor = 6a7c68
$tertiary_paletteKeyColor = 757b45
$neutral_paletteKeyColor = 757872
$neutral_variant_paletteKeyColor = 71796f
$term0 = 343433
$term1 = 799d00
$term2 = 98dd83
$term3 = bef691
$term4 = 83b694
$term5 = c6a844
$term6 = 9ed7a0
$term7 = d4dbc8
$term8 = a0a596
$term9 = 8db700
$term10 = 9ef289
$term11 = dbffbf
$term12 = acc8af
$term13 = cec06b
$term14 = aceaaa
$term15 = ffffff
$rosewater = f2f2e4
$flamingo = e3e4c5
$pink = ffd79d
$mauve = 5bd0df
$red = c5b542
$maroon = c6c177
$peach = bed696
$yellow = e3f8d0
$green = aef0b0
$teal = b1eec0
$sky = a3eac0
$sapphire = 83d8af
$blue = 67cfac
$lavender = 89dcc6
$klink = 239873
$klinkSelection = 249872
$kvisited = 008ca9
$kvisitedSelection = 008ca9
$knegative = 838f00
$knegativeSelection = 838f00
$kneutral = 82bb1e
$kneutralSelection = 84bb1b
$kpositive = 4dbf68
$kpositiveSelection = 4fbf67
$text = e0e8dc
$subtext1 = a5ada2
$subtext0 = 70786e
$overlay2 = 626960
$overlay1 = 535951
$overlay0 = 454b44
$surface2 = 383d36
$surface1 = 2a2e29
$surface0 = 1b1f1a
$base = 0c0f0b
$mantle = 0c0f0b
$crust = 0b0e0a
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
